name: Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.11'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        cache: pip
        cache-dependency-path: poetry.lock
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v3
    - run: poetry install --no-interaction
    - uses: Yuri6037/Action-FakeTTY@v1.1
    - name: Test on ${{ runner.os }}
      if: ${{ runner.os == 'Windows' }}
      run: poetry run task test
    - name: Test on ${{ runner.os }} & publish code coverage
      if: ${{ runner.os != 'Windows' && env.CC_TEST_REPORTER_ID != '' }}
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        PYTHONUNBUFFERED: 1
      with:
        coverageCommand: faketty poetry run task test:ci
        coverageLocations: ${{github.workspace}}/cov.xml:coverage.py
        debug: true
